(function(){var l=void 0,m=true,n=null,p=false,q=this;
function aa(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array)return"array";else if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if(c=="[object Window]")return"object";if(c=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";if(c=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if(b=="function"&&typeof a.call=="undefined")return"object";return b};function ba(a){a=String(a);if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/"[^"\\\n\r\u2028\u2029\x00-\x08\x10-\x1f\x80-\x9f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);}function ca(){}function da(a){var b=[];t(new ca,a,b);return b.join("")}
function t(a,b,c){switch(typeof b){case "string":ea(b,c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(b==n){c.push("null");break}if(aa(b)=="array"){var d=b.length;c.push("[");for(var e="",f=0;f<d;f++)c.push(e),t(a,b[f],c),e=",";c.push("]");break}c.push("{");d="";for(e in b)Object.prototype.hasOwnProperty.call(b,e)&&(f=b[e],typeof f!="function"&&(c.push(d),ea(e,c),c.push(":"),t(a,f,c),d=","));
c.push("}");break;case "function":break;default:throw Error("Unknown type: "+typeof b);}}var u={'"':'\\"',"\\":"\\\\","/":"\\/","\u0008":"\\b","\u000c":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\u000b":"\\u000b"},fa=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;function ea(a,b){b.push('"',a.replace(fa,function(a){if(a in u)return u[a];var b=a.charCodeAt(0),e="\\u";b<16?e+="000":b<256?e+="00":b<4096&&(e+="0");return u[a]=e+b.toString(16)}),'"')};function ga(a){return window.btoa(encodeURIComponent(a).replace(/%([0-9A-F]{2})/g,function(a,c){return String.fromCharCode("0x"+c)}))}function ha(a){return decodeURIComponent(window.atob(a).split("").map(function(a){return"%"+("00"+a.charCodeAt(0).toString(16)).slice(-2)}).join(""))}function v(a,b,c){var d=Array.prototype.slice,e=d.call(arguments,2);return function(){return a.apply(b,e.concat(d.call(arguments)))}}function y(a){return typeof a!=="undefined"}
function A(a){return typeof a==="string"}function B(){return(new Date).getTime()}function C(a,b){if((!!a&&a.constructor===Object)===m)for(var c in a){if(a.hasOwnProperty(c)&&b(a[c],c)===p)break}else{c=0;for(var d=a.length;c<d;c++)if(b(a[c],c)===p)break}}function ia(a,b){var c;a:{c=0;for(var d=a.length;c<d;c++)if(b(a[c]))break a;c=-1}if(c>-1)return a[c]}var ja=q.setInterval,D=q.clearInterval,ka=q.setTimeout;function la(a){ka(a,0)}
function ma(){var a=y(q.XDomainRequest);return y(q.XMLHttpRequest)&&"withCredentials"in new q.XMLHttpRequest?new q.XMLHttpRequest:a?new q.XDomainRequest:n}function na(a,b,c){var d=ma();d===n?c(n):(oa(function(){d.open("GET",a,m)}),d.onload=function(){d.responseText?b(d):c(d)},d.onerror=function(){c(d,"onerror")},d.timeout=1E3,d.ontimeout=function(){c(d,"timeout")},la(function(){oa(function(){d.send(n)})}))}function oa(a){try{a()}catch(b){}};function pa(a){var b={};a&&(a.charAt(0)=="?"&&(a=a.substring(1)),a=a.replace(/\+/g," "),C(a.split(/[&;]/g),function(a){a=a.split("=");b[decodeURIComponent(a[0])]=decodeURIComponent(a[1])}));return b}function qa(a,b){return!b?m:a==="http:"&&b==="80"||a==="https:"&&b==="443"};function ra(){var a=E;C(document.getElementsByTagName("script"),function(b){if(typeof b.src==="string"&&b.src.match(/chartbeat.js/))return b=pa(b.src.split("?")[1]),a.uid=a.uid||b.uid,a.domain=a.domain||b.domain,p})};var F={};F.H=function(a){try{F.create("_cb_test","1",1,a);var b=F.b("_cb_test");F.remove("_cb_test",a);return b==="1"}catch(c){return p}};F.b=function(a){a+="=";var b="";C(document.cookie.split(";"),function(c){for(;c.charAt(0)===" ";)c=c.substring(1,c.length);if(c.indexOf(a)===0)return b=c.substring(a.length,c.length),p});return b};
F.create=function(a,b,c,d){var e=q._sf_async_config;if(e&&e.noCookies)return"";e=new Date;e.setTime(B()+c*1E3);a=a+"="+b+("; expires="+e.toGMTString())+("; path="+d);return document.cookie=a};F.remove=function(a,b){return F.b(a)?F.create(a,"",-86400,b):""};var G={};G.a=function(a){var b=q._sf_async_config;if(!a&&b&&b.noCookies)return n;if(G.a.p!==l)return G.a.p;var a=B()+"",c,d;try{if((d=q.localStorage).setItem(a,a),c=d.getItem(a)===a,d.removeItem(a),c)return G.a.p=d}catch(e){}return G.a.p=n};G.b=function(a){var b=G.a();if(!b)return"";var c=b.getItem(a+"_expires");return c&&(c=+c,!isNaN(c)&&B()>c)?(G.remove(a),""):b.getItem(a)||""};
G.create=function(a,b,c){var d=G.a();if(d){var e=new Date;e.setTime(B()+c*1E3);try{d.setItem(a,b),d.setItem(a+"_expires",e.getTime())}catch(f){}}};G.remove=function(a){var b=G.a();b&&(b.removeItem(a),b.removeItem(a+"_expires"))};function H(a,b){this.u=a||"";this.h=b||"/";this.V=G.a()!==n||F.H(this.h);this.T=p;sa(this)}function sa(a){if(!F.b("_cb_ls")){var b=G.a()!==n,c=F.b("_SUPERFLY_lockout");c&&C(["","_v_","_p_"],function(b){a.create(b+"_SUPERFLY_lockout",c,600,m)});var d=F.b("_chartbeat3");d&&(a.create("_v__chartbeat3",d,34128E3,m),F.remove("_chartbeat3",a.h));b&&((b=F.b("_chartbeat2"))&&a.create("_chartbeat2",b,34128E3,m),(b=F.b("_chartbeat5"))&&a.create("_chartbeat5",b,60,m));F.create("_cb_ls","1",34128E3,a.h)}}
H.prototype.create=function(a,b,c,d){a=d?a:this.u+a;(G.a()?G:F).create(a,b,c,this.h);G.a()&&F.create(a,b,c,this.h)};H.prototype.b=function(a,b){var a=b?a:this.u+a,c=(G.a()?G:F).b(a);if(!c&&G.a()&&(c=F.b(a))&&F.b("_cb_ls")){this.T=m;var d;switch(a){case "_SUPERFLY_lockout":d=600;break;case "_chartbeat4":d=60;break;case "_cb_cp":d=60;break;case "_chartbeat3":d=34128E3;break;default:d=34128E3}G.create(a,c,d)}return c};
H.prototype.remove=function(a,b){a=b?a:this.u+a;(G.a()?G:F).remove(a,this.h);G.a()&&F.remove(a,this.h)};function I(a,b,c){a.ownerDocument||(a=a.correspondingUseElement);if(!a||!a.ownerDocument)return n;var d=a.ownerDocument.documentElement,e=0,f=y(c)?c+1:-1;A(b)?(b=b.toLowerCase(),c=function(a){return(a=a.nodeName)&&a.toLowerCase()===b}):c=b;for(;a&&a!==d&&e!==f;){if(c(a))return a;a=a.parentNode;e++}return n}var J=function(){var a=/[ \r\n\t\f\u200B]+/g;return function(b){return b&&A(b)?b.trim().replace(a," "):""}}();
function ta(a){return a.nodeName&&a.nodeName.toLowerCase()==="a"&&(!a.namespaceURI||a.namespaceURI==="http://www.w3.org/1999/xhtml")}function ua(a,b){var c=a.children,d=c.length;if(!d)return a;for(var e=b!==l?b:J(a.textContent),f=0;f<d;f++)if(J(c[f].textContent)===e)return ua(c[f],e)||a;return a}
function K(a){if(arguments.length==0)throw new TypeError("`CSS.escape` requires an argument.");for(var b=String(a),c=b.length,d=-1,e,f="",h=b.charCodeAt(0);++d<c;)e=b.charCodeAt(d),f+=e==0?"\ufffd":e>=1&&e<=31||e==127||d==0&&e>=48&&e<=57||d==1&&e>=48&&e<=57&&h==45?"\\"+e.toString(16)+" ":d==0&&c==1&&e==45?"\\"+b.charAt(d):e>=128||e==45||e==95||e>=48&&e<=57||e>=65&&e<=90||e>=97&&e<=122?b.charAt(d):"\\"+b.charAt(d);return f}
function va(a){var b=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,a=String(a);b.lastIndex=0;b.test(a)&&(a=a.replace(b,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return eval("("+a+")");throw new SyntaxError("JSON.parse");
};function wa(){var a=G.a(m);return!a?p:!!a.getItem("_cb_ip")};var xa="z";function L(){y(q._cb_shared)||(q._cb_shared={});return q._cb_shared};function M(a,b){var c=L(),c=(y(l)&&!y(c.m)?l:c.m)||[];c.push.apply(c,arguments);L().m=c};function ya(){var a=za();if(a){var b=a.href,a={hostname:"",pathname:"",search:"",protocol:"",port:"",hash:""};if(b){var c=document.createElement("a"),d=q.location;if(!/^https?:/.test(b)&&b.indexOf("javascript:")!==0&&b.indexOf("app:")<0)if(b.indexOf("//")===0)b=d.protocol+b;else if(b.indexOf("/")===0)var e=qa(d.protocol,d.port)?"":d.port,b=d.protocol+"//"+d.hostname+(e?":"+e:"")+b;else{var e=document.baseURI||d.href,f=e.indexOf("?");f===-1&&(f=e.indexOf("#"));if(f===-1)f=e.length;f=e.lastIndexOf("/",
f);b=f===-1?"/"+b:e.substr(0,f)+"/"+b}c.href=b;a.hostname=c.hostname;a.pathname=c.pathname;a.search=c.search;a.protocol=c.protocol;a.port=c.port;a.hash=c.hash;if(a.pathname.charAt(0)!=="/")a.pathname="/"+a.pathname;if(a.hostname==="")a.hostname=d.hostname;if(a.protocol==="")a.protocol=d.protocol;if(a.protocol==="javascript:")a.pathname="",a.hostname="",a.port="",a.hash="";if(qa(a.protocol,a.port)||a.port==="0")a.port=""}}return a}
function za(){var a=n;C(document.getElementsByTagName("link"),function(b){if(b.rel=="canonical")return a=b,p});return a}for(var Aa={},N=0;N<81;N++)Aa["0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-._~!$&'()*+,;=:@[]".charCodeAt(N)]=m;function Ba(a,b){if(a==="%")return"%25";var c=parseInt(b,16);return Aa[c]?String.fromCharCode(c):"%"+b.toUpperCase()}
function O(a){if(!A(a))return a;a=a.replace(/%([0-9A-Fa-f]{2})?/g,Ba);return a=a.replace(/[^0-9A-Za-z\-._~!$&'()*+,;=:@\/\[\]?#%]+/g,encodeURIComponent)};function Ca(a){var b,c;b=a.domain;c=q.location.hostname&&q.location.hostname.replace(/^www\./,"");b=(q.location.protocol==="http:"?"http:":"https:")+"//mab.chartbeat.com/mab_strategy/headline_testing/get_strategy/?host="+encodeURIComponent(b)+"&domain="+encodeURIComponent(c)+"&path=";(a=a.path)?(a=a.replace(/.*:\/\//,"").replace(/^[^/]+\//,"/"),a=a.charAt(0)!=="/"?"/"+a:a):a="/";return b+encodeURIComponent(a)}
function Da(a,b,c){var d,e,f;na(a,function(a){a=Ea(a.responseText);a=(a=ba(a))&&a.constructor===Object&&A(a.status)&&(a.data&&a.data.constructor===Object||a.data===n)?{O:a.status,i:a.data,W:a.code,X:a.message}:n;if(a===n)c();else if(a.O==="success"){d={};f=e=0;if(a.i)a.i.experiments&&(d=a.i.experiments),y(a.i.probability_is_lift)&&(e=a.i.probability_is_lift),y(a.i.probability_is_control)&&(f=a.i.probability_is_control);b(d,[e,f])}else c()},c)}
function Fa(a,b,c){var d=[],e=b.e;if(e==="l"||e==="c")b=new Ga("lift_exp","","",b,e,"","",""),b.j=m,d.push(b);return d=d.concat(Ha(a,c,e))}function Ia(a,b){var c=[new P("l",a[0],"",{},"",{},"",[]),new P("c",a[1],"",{},"",{},"",[]),new P("m",1-a[0]-a[1],"",{},"",{},"",[])];return Ja(c,b.lift_exp)||c[2]}function Ha(a,b,c){var d=[];C(a,function(a,f){var h=Ka(f,a,c,b[f]);y(h)&&d.push(h)});return d}
function Ka(a,b,c,d){var e=b.location,f=b.specific_location,h=b.type,g,i,j=b.metadata;if(A(j)&&j.length>0&&((j=va(j))&&j.version==2&&(g=j.sub_location),j&&j.version==3))g=j.sub_location,i=j.initial_content;g=y(g)?g:"";i=y(i)?i:"";var k=[];C(b.variants,function(a,b){var c=parseFloat(a.probability),e=a.content,d=a.metadata,f={},i="",h={},j="",g=[];if(A(d))(d=va(d))&&d.image_source_sets_info&&(f=d.image_source_sets_info||{}),d&&d.image_alt_attribute&&(i=d.image_alt_attribute),d&&d.image_caption&&(j=
d.image_caption),d&&d.current_image_source_info&&(h=d.current_image_source_info||{}),d&&d.crops&&(g=d.crops||[]);k.push(new P(b,c,e,f,i,h,j,g))});if(b=Ja(k,d&&d.chosenVariant))return new Ga(a,e,g,b,c,i,f,h)}function Ja(a,b){var c;y(b)&&(c=ia(a,function(a){return a.e===b}));y(c)||(c=La(a));return c}function La(a){var b=Math.random();return ia(a,function(a){b-=a.Q;return b<0})}
function Ma(a,b,c){var d=q.location.href,e=[encodeURIComponent(a),encodeURIComponent(d),b].join(",");C(c,function(a){e+=","+[a.test.e,a.test.l.e,encodeURIComponent(a.f)].join(",")});return e}function Na(a,b){if(a===b)return m;for(var c=b.split("."),d=a.split(".");c.length;){if(d.length===0)return p;if(c.pop()!==d.pop())return p}return m}
function Oa(){var a=q.document.head||q.document.getElementsByTagName("head")[0],b=q.document.createElement("style");b.id="chartbeat-flicker-control-style";b.type="text/css";b.styleSheet?b.styleSheet.cssText="body { visibility: hidden !important; }":b.appendChild(document.createTextNode("body { visibility: hidden !important; }"));a.appendChild(b)}function Pa(){return q.document.getElementById("chartbeat-flicker-control-style")||q.document.getElementById("chartbeat-body-hider")}
function Qa(){var a=Pa();a&&a.parentNode.removeChild(a)}function Ga(a,b,c,d,e,f,h,g){this.e=a;this.n=b;this.f=h;this.G=c;this.l=d;this.t=e;this.j=p;this.anchors=[];this.N=f;this.type=g}function P(a,b,c,d,e,f,h,g){this.e=a;this.Q=b;this.content=c;this.M=d||{};this.K=e;this.J=f||{};this.L=h;this.I=g}function Ra(a){var b={};b.s=a.status;b.c=a.code;b.m=a.message;var c=n;if(a.data!==n)c={},c.s=a.data.S,c.g=a.data.t,c.m=a.data.P;b.d=c;return b}
function Sa(a){if(q.document&&q.document.body)a();else var b=ja(function(){q.document&&q.document.body&&(D(b),a())},50)}var Ta=/^[a-zA-Z0-9+/]*={0,2}$/;function Ea(a){if(a&&Ta.exec(a))try{return ha(a)}catch(b){}return a}
function Ua(a){var b=a;b+=String.fromCharCode(128);for(var a=[1518500249,1859775393,2400959708,3395469782],c=1732584193,d=4023233417,e=2562383102,f=271733878,h=3285377520,g=[],i,j,k,o,s,x=Math.ceil((b.length/4+2)/16),z=[x],w=0,r;w<x;w++){z[w]=[];for(i=0;i<16;i++)z[w][i]=b.charCodeAt(w*64+i*4)<<24|b.charCodeAt(w*64+i*4+1)<<16|b.charCodeAt(w*64+i*4+2)<<8|b.charCodeAt(w*64+i*4+3)}w=(b.length-1)*8;b=x-1;z[b][14]=Math.floor(w/Math.pow(2,32));z[b][15]=w&4294967295;for(w=0;w<x;w++){for(r=0;r<16;r++)g[r]=
z[w][r];for(r=16;r<80;r++)g[r]=(g[r-3]^g[r-8]^g[r-14]^g[r-16])<<1|(g[r-3]^g[r-8]^g[r-14]^g[r-16])>>>31;b=c;i=d;j=e;k=f;o=h;for(r=0;r<80;r++)s=Math.floor(r/20),s=(b<<5|b>>>27)+(s==0?i&j^~i&k:s==1?i^j^k:s==2?i&j^i&k^j&k:i^j^k)+o+a[s]+g[r]&4294967295,o=k,k=j,j=i<<30|i>>>2,i=b,b=s;c=c+b&4294967295;d=d+i&4294967295;e=e+j&4294967295;f=f+k&4294967295;h=h+o&4294967295}a=c;if(a==0)a="A";else{a>>>=0;for(c="";a>0;)d=a%64,c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_-".charAt(d)+c,a>>>=6;
a=c}return a}function Va(){var a=document.querySelectorAll(Wa());C(a,function(a){a=Array.prototype.slice.call(a.querySelectorAll("img"));C(a,function(a){a.setAttribute("pinger-seen","true");a.getAttribute("keep-hiding")!=="true"&&a.classList.remove("cb-it-hide")})})}function Wa(){var a=Q.articleBlockSelector;return a?a:"article, section"};function Xa(a,b){for(var c=b||document.documentElement,d=[],e=n,f=a,h,g,i,j,k,o;f&&f!==c;){h=f.nodeName.toLowerCase();e=f;g=e.nodeName;if((f=f.parentNode)&&f!==document.documentElement){i=f.children;j=0;for(k=0,o=i.length;k<o;k++){if(e===i[k]){h+="["+(1+k-j)+"]";break}i[k].nodeName!==g&&j++}}d.unshift(h)}return d.join("/")}
var R=function(){function a(a,b,c){b==="href"?(a=a.href||"",c=c||"",a=a.replace(d,""),c=c.replace(d,"")):a=a.getAttribute(b);return a===c}var b=/^\*\[@id='(.+?)'\](?:\[@([a-z-]+)='(.*)'\])?$/,c=/^([a-z][a-z0-9-]*)\[(\d+)\](?:\[@([a-z-]+)='(.*)'\])?$/,d=/^http(s)?\:\/\//;return function(d,f){var h=n;a:{for(var h=0,g=d.indexOf("/"),i=d.indexOf("'"),j=[];g!==-1;)if(i!==-1&&i<g){i=d.indexOf("'",i+1);if(i==-1){h=n;break a}g=d.indexOf("/",i+1);i=d.indexOf("'",i+1)}else j.push(d.substring(h,g)),h=g+1,g=
d.indexOf("/",h);h<d.length&&j.push(d.substring(h,d.length));h=j}if(!h||h.length==0)return f?f:n;var k,o,s,x,z,i=h.shift();if(f)g=f;else{if(i==="body")g=document.body;else{k=b.exec(i);if(!k)return n;g=document.getElementById(k[1]);if(!g)return n;o=k[2];k=k[3];if(o&&!a(g,o,k))return n}i=h.shift()}for(;y(i);){k=c.exec(i);if(!k)return n;i=k[1];j=parseInt(k[2],10);o=k[3];k=k[4];if(isNaN(j))return n;s=g.children;z=s.length;if(z===0)return n;for(x=0;x<z;x++){if(s[x].nodeName&&s[x].nodeName.toLowerCase()===
i&&(j--,j===0)){g=s[x];if(o&&!a(g,o,k))return n;break}if(x===z-1)return n}i=h.shift()}return g}}();function Ya(a){if(!("querySelectorAll"in document))return[];var b;b=/a\[@href='(.+?)'\sor\sstarts-with\(.+,\s?'(.+?)'\)\]/.exec(a);a=/^a\[@href='(.+?)'\]$/.exec(a);if(!b&&!a)return n;b=document.querySelectorAll(b?'a[href="'+b[1]+'"],a[href^="'+b[2]+'"]':'a[href="'+a[1]+'"]');b.length<1&&(b=n);return b?Array.prototype.slice.call(b):[]}
function Za(a){var b=n,b=I(a,function(a){return a.id}),c=Xa(a,b);b&&(c&&(c="/"+c),c="*[@id='"+b.id+"']"+c);c+="[@href='"+a.href+"']";return c};function S(a){this.r=a;this.o=[];var b=this.r,a=b.topStorageDomain,b=b.domain,c=q.location.hostname;this.U=a?a:Na(c,b)?b:c.replace(/^www\./,"");this.F=new H("_t_",this.r.cookiePath||"/");this.k=T;a=xa;L()[a]=m}
function $a(a){if(!a.B){a.B=m;var b=a.D,c=a.z,d=Ea(a.F.b("tests")),e={};d.length>0&&(e=ba(d));var f=Ia(c,e);a.o=Fa(b,f,e);var h=a.o,g={domain:"."+a.U,A:6E4,path:"/"};a.q=function(a){var b,a=a||window.event;if(b=!a?n:I(a.target||a.srcElement,ta,10))if(a=ab(b,h),a.length){var c;if(b===n||typeof b==="undefined")c="unknown";else if(b.tagName==="A"&&b.href)c=b.href;c=Ma(c,a[0].test.t,a);a=(a=F.b("_chartbeat6"))?a.split("::"):[];a.length>=10&&a.splice(0,a.length-10+1);a.push(c);c="_chartbeat6="+a.join("::");
a="";g&&g.constructor===Object&&(g.A&&(b=new Date,b.setTime(b.getTime()+g.A),a+="; expires="+b.toGMTString()),g.domain&&(a+="; domain="+g.domain),g.path&&(a+="; path="+g.path));document.cookie=c+a}};a=v(function(){var a=this.q,b=q.document.body;b.addEventListener?b.addEventListener("click",a,m):b.attachEvent&&b.attachEvent("onclick",a);bb(this,h,f.e)},a);Sa(a)}}
function bb(a,b,c){var d=B(),e=v(function(){var a=B()-d>=5E3,e=q.document.readyState==="complete"||q.document.readyState!=="loading"&&!q.document.documentElement.doScroll,g;a||(g=cb(b,c));if(a||g||e)D(this.v),U(this)},a);a.v=ja(e,50);e()}
function U(a){Qa();var b={},c=[],d=p,e="m";C(a.o,function(a){if(a.e==="lift_exp")e=a.l.e;if(a.j){d=m;var f=[];C(a.anchors,function(a){f.push(a.f)});b[a.e]={chosenVariant:a.l.e,specificLocation:f}}else c.push(a.e)});if(d)b.lift_exp=e,a.F.create("tests",ga(da(b)),3600),e==="m"&&delete b.lift_exp;var f={status:db,data:n,code:l,message:l};a.k!==T?(f.status=eb,f.code=a.k):(a={S:b,t:e,P:c},f.status=fb,f.data=a);M(["t",Ra(f)])}
function gb(a){var b=a.r;M(["ev",function(){a.terminate()}]);M(["sv",function(){hb(a,b)}])}S.prototype.R=function(a){if(Object.prototype.toString.call(a)==="[object Array]"&&A(a[0])&&a[0]==="readyForTesting")a[1]?$a(this):this.C=p};function ib(a){a.k=jb;U(a)}function kb(a){a.k=lb;U(a)}
S.prototype.terminate=function(){this.k=T;var a=this.q,b=q.document.body;b.removeEventListener?b.removeEventListener("click",a,m):b.detachEvent&&b.detachEvent("onclick",a);this.q=l;D(this.v);this.v=n;this.o=[];this.z=this.D=n;this.B=p};
function hb(a,b){gb(a);if(wa())ib(a);else if("srcset"in document.createElement("img")){var c=Ca(b);if(y(c))y(b.flickerControl)||(b.flickerControl=m),b.flickerControl&&(ka(Qa,1E3),Pa()||Oa()),Da(c,function(b,c){a:{var f=q.chartbeatFlicker;if(f){if(f.timeoutFlag)break a;f.strategyFetched=m}a.D=b;a.z=c;a.C=m;for(var f=v(a.R,a),h=q._cbm||[];h.length;)f(h.shift());q._cbm={push:f};a.C&&$a(a)}},function(){})}else kb(a)}
function cb(a,b){var c=[];C(a,function(a,d){c.push(p);if(a.j)c[d]=m;else if(!a.f||a.f===a.n){var h=R(a.n);if(h)var g=R(a.G,h);if(h&&g)c[d]=m,b!=="c"&&mb(g,a),a.anchors=[{element:h,f:Ua(a.n)}],a.j=m}else{a.anchors=[];var i=a.N;(h=Ya(a.n))&&h.length>0&&C(h,function(g){if(g)var h=R(a.G,g);var o;h&&(o=J(h.textContent),o==i?ua(h,o)!=h&&(h=n):h=n);if(g&&h)c[d]=m,b!=="c"&&mb(h,a),a.anchors.push({element:g,f:Ua(Za(g))}),a.j=m})}});Va();var d=document.getElementById("chartbeat-flicker-control-style-ht");d&&
d.parentNode.removeChild(d);return c.indexOf(p)===-1}
function ab(a,b){var c=[],d=n,e=101,f=p;C(b,function(b){!f&&!b.w&&C(b.anchors,function(c){if(!f)if(c.element===a)d={test:b,f:c.f},f=m;else if(c.element.href===a.href){var i;var j=c.element.getBoundingClientRect(),k=a.getBoundingClientRect();j.right-j.left>0&&j.bottom-j.top>0&&k.right-k.left>0&&k.bottom-k.top>0?(i=Math.max(j.left,k.left)-Math.min(j.right,k.right),j=Math.max(j.top,k.top)-Math.min(j.bottom,k.bottom),i=i<=0?Math.max(j,0):j<=0?i:Math.sqrt(i*i+j*j)):i=l;i<e&&(d={test:b,f:c.f},e=i)}})});
d&&c.push(d);return c}
function mb(a,b){var c=b.l,d=c.content,e=c.M,f=c.K,h=c.J,g=c.L,i=c.I,c=b.type;if("textContent"in document.createElement("b")&&a.textContent.trim())if(c.indexOf("image")<0||!e||!Object.keys(e).length||!h||!Object.keys(h).length)a.textContent=d;else{var j=Q.lazyLoadSrcsetAttribute||"data-srcset";b.w=m;C(Object.keys(e),function(c){var o=e[c];if(o&&!isNaN(o.width)&&!isNaN(o.height)&&!isNaN(h.width)&&!isNaN(h.height)){var s;i&&i.length>1?C(i,function(a){Math.abs(a.width/a.height-o.width/o.height)<0.015&&
(s=a.newSrcSet||a.src)}):Math.abs(h.width/h.height-o.width/o.height)<0.015&&(s=o.newSrcSet||o.src);if(s){a.textContent=d;var x=document.querySelectorAll('[srcset="'+K(c)+'"]'),z=document.querySelectorAll("["+j+' = "'+K(c)+'"]'),c=document.querySelectorAll('[src="'+K(c)+'"]');Array.prototype.forEach.call(x,function(a){nb(a,"srcset",s,g,f);ob(a)});Array.prototype.forEach.call(z,function(a){nb(a,j,s,g,f)});Array.prototype.forEach.call(c,function(a){nb(a,"src",s,g,f);ob(a)});b.w=p}}})}}
function nb(a,b,c,d,e){var f=a.parentNode.querySelector("img"),h=Wa(),g=a.parentNode.querySelector("img");a.setAttribute(b,c);g.setAttribute("alt",e);if(a=I(a,h))if(a=a.querySelector("figcaption"))a.innerHTML=d;f.setAttribute("keep-hiding","true")}function ob(a){var b=a.parentNode.querySelector("img");b.classList.add("cb-it-hide");b.addEventListener("load",function(){b.classList.remove("cb-it-hide");b.removeAttribute("keep-hiding");b.removeAttribute("pinger-seen")})}
var T=0,jb=2,lb=4,fb="s",eb="e",db="f";if(!F.b("cb_optout")){var Q=q._sf_async_config,E=Q;ra();var pb=!!E.useCanonical,qb;a:{if(E.useCanonicalDomain&&pb){var rb,sb=ya();if(rb=!sb?sb:sb.hostname){qb=rb;break a}}qb=q.location.hostname}E.title=E.title||document.title;E.domain=E.domain||qb;var tb=E,V;if(E.path)V=O(E.path);else a:{var W=n;if(pb){var X=ya();if(W=!X?X:O(X.pathname)+X.search+X.hash){V=W;break a}}var ub=q.location,W=O(ub.pathname),Y=ub.search||"",Y=Y.replace(/PHPSESSID=[^&]+/,""),Z=/&utm_[^=]+=[^&]+/ig,$=Z.exec(ub.search);$&&(Y=
Y.replace(Z,""));Z=/\?utm_[^=]+=[^&]+(.*)/i;($=Z.exec(Y))&&(Y=Y.replace(Z,$[1]!=""?"?"+$[1]:""));V=W+Y}tb.path=V;E.domain=E.domain&&E.domain.replace(/^www\./,"");if("textContent"in document.createElement("b")&&"querySelectorAll"in document&&"atob"in window&&"btoa"in window){var vb=new S(Q);hb(vb,Q)}};})();
